### ISSUE TITLE
滚动顺序的圆圈

### ISSUE THREAD

**Issue by 695161802** [kainstar/vue-fullpage#4]
圆点怎么改颜色呢

**Comment by hzxszsk** [comment]
修改PageController.vue文件下的样式内容，改成你想要的颜色即可：
```css
/* 一般情况下的颜色 */
.controller-item {
    background-color: rgba(255, 255, 255, 0.3);
}
/* 鼠标移上去时候的颜色 */
.controller-item:hover {
    background-color: rgba(255, 255, 255, 0.7);
}
/* 是当前页的情况下的颜色 */
.controller-item.current {
    background-color: rgba(255, 255, 255, 1);
}
```
